### PR TITLE
Add tutorial for getting SMS messages from in game

### PR DESCRIPTION
**Pull request by tedivm**

### CODE REVIEW

**Comment by lf-** [comment]
It would be nice if there were instructions for non-docker users.

**Comment by tedivm** [comment]
@xyzzy529 - you can make edits! Just clone this repository, add my fork as an upstream, and then branch from `tedivm:notify` and make a pull request to it.

**Comment by tedivm** [comment]
Instructions for non-docker users added.

**Comment by tedivm** [comment]
@artch - what does "needs-comments" mean? Should I request more reviews from people?

**Comment by kotarou** [comment]
Looks pretty good. Might be good to explicitly link https://support.twilio.com/hc/en-us/articles/223183068-Twilio-international-phone-number-availability-and-their-capabilities and explicitly mention that users from  some countries will not be able to get sms-capable twilo numbers.

**Comment by ButAds** [comment]
I tried this interface. It works really well, the documentation is up to spec on my opinion.

**Comment by artch** [comment]
Since this article is about external service using unofficial Web API, we'll postpone it until API keys are released, so that the published revision of the article contains their proper usage as well.

**Comment by tedivm** [comment]
That's fine, I need to update it with some changes anyways.

Is there a rough eta for API keys? Like end of the year?

**Comment by o4kapuk** [comment]
@tedivm Auth tokens released https://blog.screeps.com/2017/12/auth-tokens/
Is this article still a thing?

**Comment by tedivm** [comment]
I'll deal with it at some point but for the most part I'm not really playing or contributing to screeps as I build out the startup I'm in.

**Pull request closed without merging**
