### PR TITLE
Remove credentials from gruntfile for better security

### PR DESCRIPTION
**Pull request by tedivm**

### CODE REVIEW

**Comment by artch** [comment]
I think this should be considered as advanced usage and put into [your contributed article](https://github.com/screeps/docs/pull/19). We can make a link to that article from this page though.

**Comment by tedivm** [comment]
The problem is that people are reading this article, creating a gruntfile, and then uploading their code to public repositories. I do occasionally searches to notify people but a malicious person could use this to take over someones account. At the very least this article should have a warning not to upload passwords to github and a link to the advanced article.

**Comment by artch** [comment]
> At the very least this article should have a warning not to upload passwords to github and a link to the advanced article.

This is exactly what I meant.

**Comment by tedivm** [comment]
KK- once the contributed article is accepted I'll make a new pull request with that notice and the link.

**Comment by xyzzy529** [comment]
Another way to deal with the security is to add the `gruntfile.js` to the `.gitignore`

Also, change the `src` line to exclude the gruntfile in the upload:
`src: ['./*.js', '!./gruntfile.js']`

**Pull request closed without merging**
